# Merge
In this notebook, I merged two different datasets: MotherJones and GunViolenceArchive.

Merging data is processed in terms of GunViolenceArchive dataset.

In [0]:
import pandas as pd

In [0]:
MJ = pd.read_csv("/content/drive/My Drive/Project/data_historical/MJ/MotherJones.csv")
df = pd.read_csv("/content/drive/My Drive/Project/data_historical/4coordinate.csv", index_col=0)

In [0]:
df.date = pd.to_datetime(df.date)
df = df.set_index('date')

MJ.date = pd.to_datetime(MJ.date)
MJ = MJ.set_index('date')

In [49]:
df['location'] = df['city'] + ", " + df['state']
df.head()

                                                          adr  ...              location
date                                                           ...
2014-01-01  Rockingham Street and Berkley Avenue Extended ...  ...     Norfolk, Virginia
2014-01-03  Farmers Boulevard and 133rd Avenue Queens New ...  ...      Queens, New York
2014-01-05                    829 Parade St Erie Pennsylvania  ...    Erie, Pennsylvania
2014-01-11         3430 W. Capitol Street Jackson Mississippi  ...  Jackson, Mississippi
2014-01-12                University Drive Huntsville Alabama  ...   Huntsville, Alabama

[5 rows x 10 columns]

In [50]:
MJ.head()

                                              case  ...  year
date                                                ...
2020-02-26                   Molson Coors shooting  ...  2020
2019-12-10      Jersey City kosher market shooting  ...  2019
2019-12-06           Pensacola Naval base shooting  ...  2019
2019-08-31           Odessa-Midland shooting spree  ...  2019
2019-08-04  Dayton entertainment district shooting  ...  2019

[5 rows x 23 columns]

## Rule
From several trials, I decided to use location and date to merging data.   
Coordinates of GunViolenceArchive dataset from Googlemaps is not perfectly matched with MotherJones dataset. (in three decimal points, it works but it is better to use location -- city + state.)

In [0]:
new = pd.merge(df, MJ, how = 'left', on = ['location', 'date'])

In [52]:
new.head()

                                                          adr  ...  year
date                                                           ...
2014-01-01  Rockingham Street and Berkley Avenue Extended ...  ...   NaN
2014-01-03  Farmers Boulevard and 133rd Avenue Queens New ...  ...   NaN
2014-01-05                    829 Parade St Erie Pennsylvania  ...   NaN
2014-01-11         3430 W. Capitol Street Jackson Mississippi  ...   NaN
2014-01-12                University Drive Huntsville Alabama  ...   NaN

[5 rows x 32 columns]

## delete variables  
I removed some overlapping or useless variables.

In [0]:
del new['fatalities']
del new['injured']
del new['latitude']
del new['longitude']
del new['year']
del new['sources']
del new['location.1'] 
del new['total_victims']
del new['street']
del new['city']
del new['location']

In [54]:
new.head()

                                                          adr  ...  type
date                                                           ...
2014-01-01  Rockingham Street and Berkley Avenue Extended ...  ...   NaN
2014-01-03  Farmers Boulevard and 133rd Avenue Queens New ...  ...   NaN
2014-01-05                    829 Parade St Erie Pennsylvania  ...   NaN
2014-01-11         3430 W. Capitol Street Jackson Mississippi  ...   NaN
2014-01-12                University Drive Huntsville Alabama  ...   NaN

[5 rows x 21 columns]

In [0]:
new.to_csv('new.csv')
new.to_csv('/content/drive/My Drive/Project/data_historical/5merge.csv')
MJ.to_csv('/content/drive/My Drive/Project/data_historical/MJ/MJ.csv')